export const FETCH_PERSON_START = 'FETCH_PERSON_START';
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAILED = 'FETCH_PERSON_FAILED';

export const LOAD_MORE_PERSONS_START = 'LOAD_MORE_PERSONS_START';
export const LOAD_MORE_PERSONS_SUCCESS = 'LOAD_MORE_PERSONS_SUCCESS';
export const LOAD_MORE_PERSONS_FAILED = 'LOAD_MORE_PERSONS_FAILED';